// <auto-generated />
namespace ToolChest_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedsetterstoratings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsetterstoratings));
        
        string IMigrationMetadata.Id
        {
            get { return "202102240620486_addedsetterstoratings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
